# STAGE 1: BUILD
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Smt.Producer.csproj .
RUN dotnet restore Smt.Producer.csproj

COPY . .
RUN dotnet publish Smt.Producer.csproj -c Release -o /app/publish

# STAGE 2: RUN
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Smt.Producer.dll"]